### ISSUE TITLE
processCssUrls is not working as expected

### ISSUE THREAD

**Issue by jakewhiteley** [mvdnbrk/laravel-mix-tailwindcss#4]
I would expect the below code to copy `fonts/Inter-Regular.woff2` into my configured public directory, and add it to the `mix-manifest.json`.

```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	@font-face {
		font-family: 'Inter';
		font-style:  normal;
		font-weight: 400;
		font-display: swap;
		src: url("../fonts/Inter-Regular.woff2") format("woff2"),
			url("../fonts/Inter-Regular.woff") format("woff");
	}
}
```

It doesn't however - no font files are moved and no entry is added.

If I remove `.tailwind()` from my webpack-config, then the font file is moved and versioned correctly.

My config:
```js
let mix = require('laravel-mix')
require('mix-tailwindcss')

mix.js('docs/assets/js/index.js', 'assets/js')
	.setPublicPath('_site')
	.version()
	.sass('docs/assets/sass/index.scss', 'assets/css')
	.tailwind('./docs/tailwind.config.js')

if (!mix.inProduction()) {
	mix.browserSync({
		server: "_site",
		files: ["_site/**/*.html", "_site/assets/css/*.css", "_site/assets/js/*.js"]
	})
}
```
